package com.aiun.order.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

import java.io.Serializable;
import java.util.Date;

/**
 * @author lenovo
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode
@Accessors(chain = true)
@ApiModel(value = "cart对象", description = "购物车表")
public class Cart implements Serializable {
    /**
     * 主键
     */
    @ApiModelProperty(value = "购物车表主键")
    private Integer id;

    /**
     * 用户 id
     */
    @ApiModelProperty(value = "用户 id")
    private Integer userId;

    /**
     * 产品 id
     */
    @ApiModelProperty(value = "产品 id")
    private Integer productId;

    /**
     * 产品数量
     */
    @ApiModelProperty(value = "产品数量")
    private Integer quantity;

    /**
     * 购物车中产品选中状态
     */
    @ApiModelProperty(value = "购物车中产品选中状态")
    private Integer checked;

    /**
     * 创建时间
     */
    @JsonFormat(pattern="yyyy-MM-dd")
    @ApiModelProperty(value = "创建时间")
    private Date createTime;

    /**
     * 更新时间
     */
    @JsonFormat(pattern="yyyy-MM-dd")
    @ApiModelProperty(value = "更新时间")
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_cart
     */
    private static final long serialVersionUID = 1L;

}