package com.aiun.order.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * @author lenovo
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode
@Accessors(chain = true)
@ApiModel(value = "Order对象", description = "Order表")
public class Order implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.id
     */
    @ApiModelProperty(value = "订单表主键")
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.order_no
     */
    @ApiModelProperty(value = "订单号")
    private Long orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.user_id
     */
    @ApiModelProperty(value = "用户 id")
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.shipping_id
     */
    @ApiModelProperty(value = "地址 id")
    private Integer shippingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.payment
     */
    @ApiModelProperty(value = "支付金额")
    private BigDecimal payment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.payment_type
     */
    @ApiModelProperty(value = "支付类型")
    private Integer paymentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.postage
     */
    @ApiModelProperty(value = "库存")
    private Integer postage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.status
     */
    @ApiModelProperty(value = "支付状态")
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.payment_time
     */
    @JsonFormat(pattern="yyyy-MM-dd")
    @ApiModelProperty(value = "支付时间")
    private Date paymentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.send_time
     */
    @JsonFormat(pattern="yyyy-MM-dd")
    @ApiModelProperty(value = "发货时间")
    private Date sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.end_time
     */
    @JsonFormat(pattern="yyyy-MM-dd")
    @ApiModelProperty(value = "订单结束时间")
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.close_time
     */
    @JsonFormat(pattern="yyyy-MM-dd")
    @ApiModelProperty(value = "交易关闭时间")
    private Date closeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.create_time
     *
     * @mbg.generated
     */
    @JsonFormat(pattern="yyyy-MM-dd")
    @ApiModelProperty(value = "表创建时间")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.update_time
     *
     * @mbg.generated
     */
    @JsonFormat(pattern="yyyy-MM-dd")
    @ApiModelProperty(value = "表更新时间")
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_order
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}