package com.aiun.order.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

@Data
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode
@Accessors(chain = true)
@ApiModel(value = "OrderItem对象", description = "订单详情表")
public class OrderItem implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order_item.id
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "主键")
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order_item.user_id
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "用户 id")
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order_item.order_no
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "订单号")
    private Long orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order_item.product_id
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "产品 id")
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order_item.product_name
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "产品名")
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order_item.product_image
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "产品主图")
    private String productImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order_item.current_unit_price
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "产品当前的价格")
    private BigDecimal currentUnitPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order_item.quantity
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "数量")
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order_item.total_price
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "商品总价")
    private BigDecimal totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order_item.create_time
     *
     * @mbg.generated
     */
    @JsonFormat(pattern="yyyy-MM-dd")
    @ApiModelProperty(value = "创建时间")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order_item.update_time
     *
     * @mbg.generated
     */
    @JsonFormat(pattern="yyyy-MM-dd")
    @ApiModelProperty(value = "更新时间")
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_order_item
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}