package com.aiun.product.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

@Data
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode
@Accessors(chain = true)
@ApiModel(value = "Product对象", description = "产品表")
public class Product implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_product.id
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "主键 id")
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_product.category_id
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "分类 id，对应trade_category表的主键")
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_product.name
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "产品名")
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_product.subtitle
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "产品标题")
    private String subtitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_product.main_image
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "产品主图，产品主图,url相对地址")
    private String mainImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_product.sub_images
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "产品副图，图片地址,json格式,扩展用")
    private String subImages;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_product.detail
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "产品详情")
    private String detail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_product.price
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "产品价格，单位-元保留两位小数")
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_product.stock
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "产品库存")
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_product.status
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "产品状态，1-在售 2-下架 3-删除")
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_product.create_time
     *
     * @mbg.generated
     */
    @JsonFormat(pattern="yyyy-MM-dd")
    @ApiModelProperty(value = "创建时间")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_product.update_time
     *
     * @mbg.generated
     */
    @JsonFormat(pattern="yyyy-MM-dd")
    @ApiModelProperty(value = "更新时间")
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_product
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}